import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/server/header/Header";
import Footer from "./components/server/footer/Footer";
import { Happy_Monkey, Rubik } from "next/font/google";

const font_hm = Happy_Monkey({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-monkey'
});
const font_rubik = Rubik({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik'
}) ;

const lang:string = 'fr';

export const metadata: Metadata = {
  title: "Texturae",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={lang} data-theme="light" className={`${font_hm.variable} ${font_rubik.variable}`}>
      <body className="relative">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
